/// With oauth enabled, the dummy token needs to be replaced by a real token.
/// Use Google OAuth2 Playground to get a token.
///
/// * Go to https://developers.google.com/oauthplayground/
/// * Select and authorize the scopes:
///     * https://www.googleapis.com/auth/userinfo.email
///     * https://www.googleapis.com/auth/userinfo.profile
/// * Click "Exchange authorization code for tokens"
/// * Copy the id token and replace the dummy token below.


/// GET all sessions
GET http://localhost:3000/api/v1/sessions/
Authorization: Bearer dummy

###

/// Update sessions
POST http://localhost:3000/api/v1/sessions/
Authorization: Bearer dummy

###

/// Get current user
GET http://localhost:3000/api/v1/users/me
Authorization: Bearer dummy


###

/// Join session
GET http://localhost:3000/api/v1/sessions/13ff71bb-a685-4477-8ef1-c3a46ddba62b/join
Authorization: Bearer dummy

###

/// Get session
GET http://localhost:3000/api/v1/sessions/13ff71bb-a685-4477-8ef1-c3a46ddba62b
Authorization: Bearer dummy

###

/// Leave session
GET http://localhost:3000/api/v1/sessions/13ff71bb-a685-4477-8ef1-c3a46ddba62b/leave
Authorization: Bearer dummy

###
