version: '3.9'
services:
  db:
    image: mariadb@sha256:1e4ec03d1b73af8e7a63137b8ef4820ac7d54c654a1e99eb76235f210f7f0a06
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: javazone
      MYSQL_USER: javazone
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"

  pg:
    image: postgres:17@sha256:4d89c904835259bc58876520e56267ca07a4ebd6a027f7814bbbf91b50d685be
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: javazone
    ports:
      - "5432:5432"

  adminer:
    image: adminer@sha256:becd3a16f17d537547d613523246125f3dd73effeb109e3cefa6124996bfbbd2
    restart: always
    ports:
      - 8080:8080
