version: '3.9'
services:
  db:
    image: mariadb@sha256:bfb1298c06cd15f446f1c59600b3a856dae861705d1a2bd2a00edbd6c74ba748
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: javazone
      MYSQL_USER: javazone
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
