version: '3.9'
services:
  db:
    image: mariadb@sha256:fcc7fcd7114adb5d41f14d116b8aac45f94280d2babfbbb71b4782922ee6d8d4
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: javazone
      MYSQL_USER: javazone
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"

  pg:
    image: postgres:16
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: javazone
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
