version: '3.9'
services:
  db:
    image: mariadb@sha256:2bcbaec92bd9d4f6591bc8103d3a8e6d0512ee2235506e47a2e129d190444405
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: javazone
      MYSQL_USER: javazone
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"

  pg:
    image: postgres:17@sha256:4d89c904835259bc58876520e56267ca07a4ebd6a027f7814bbbf91b50d685be
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: javazone
    ports:
      - "5432:5432"

  adminer:
    image: adminer@sha256:becd3a16f17d537547d613523246125f3dd73effeb109e3cefa6124996bfbbd2
    restart: always
    ports:
      - 8080:8080
