version: '3.9'
services:
  db:
    image: mariadb@sha256:310d29fbb58169dcddb384b0ff138edb081e2773d6e2eceb976b3668089f2f84
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: javazone
      MYSQL_USER: javazone
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
