services:
  pg:
    image: postgres:18@sha256:9685e09573f19eeb99d259547a1cb7a7a77cd15877f55f51e215ad06edf5c721
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: javazone
    ports:
      - "5432:5432"

  adminer:
    image: adminer@sha256:63db2157610c1794ec9a0383e5b64eb3cf3b738f856ff68dd0b1f1f1e0413a57
    restart: always
    ports:
      - 8080:8080

  javazone:
    image: ttl.sh/mortenlj-javazone:1h@sha256:d2ad1cd362bf107baa06c1285af60e1e66cd84f503e453bd519b7d57633427bf
    restart: always
    depends_on:
      - pg
    ports:
      - "3000:3000"
    env_file:
      - .debugenv
    environment:
      BIND_ADDRESS: "0.0.0.0"
      DATABASE__URL: postgresql+psycopg://javazone:password@pg:5432/javazone
    profiles:
      - ttl
