---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: javazone
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
  labels:
    app: javazone
spec:
  rules:
    - host: javazone.home.ibidem.no
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: javazone
                port:
                  name: http
  tls:
    - hosts:
      - javazone.home.ibidem.no
      secretName: javazone-ingress-cert
