apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: javazone
  namespace: default
  labels:
    app: javazone
spec:
  encryptedData:
    OAUTH__CLIENT_ID: AgB/7c72GH7vgfPooLNHsGXEsIRP/8iDgVZ2+Tszg6A5PL39AsL20hVkwr3PFiNi5XGEkoOLC6XLwiGEOF/xJhmuQmmWLZLj3K8aT1xiQZgxo53lSCcE8iSX8NwavqQsexnTsjHSbryULlVgimflOl48r2Tag2aFjq3BS8S1XqJCGq6qPRs9me46amC+G2lYhHYtC8Qdif2SH4a5nerIAcfZe+GeUX6PyGm2fPTYcnnp+kwseUjxhWh3fys2AUA0Lg/amcrzTLGevDxwHidISvVloDIHZ1Hh+BdW/yPjm58lpUHCUkHOFxVt0k2J2J5JC9JN5nwP9DhxPcBv6DEEjd+YCyB9jOEvrVh1+9zfHwipa3LSSRq6qj5fbNGmajIirsGoy3s0r+TJqZWy99aofa4vPtVS9F9pVexdSg1IQyvR9Sh+7JtwKfQuscPPWJ89NbdMIGAOJ3RgUlM8AgnFjzN2aeWlMdSoBcvrDaT3vwwsx0OkKrXDjig9SUZ8bHLSz1vR2XlmcFqAe+ebHZRI/FiLpIDxLMx8TWV+gr1A/6KKcg4LqiC9ubx1SHuuVkouaptpRmxO/rCJ45LMK5Y40LbKz6230kQQIt9ZlfMURvF23K+kx6TkaDimpjkJnA1fUV3pVf835VV8oiROuNLmYqUzZzymgnWiMOSLwFf+C5Ts57h7tPdp01w9vSclIlsmzovBDTbigcxFZh/wagNBCMtyM2xppt/f0/8xPlIK4jYhQIHdm91wyECAxSNB9NsTHikOFKsB0lCwrfZ0dsVzS0i0Jl2vEqVRypQ=
    OAUTH__CLIENT_SECRET: AgBHNwFlUgG42mKo9EtlR/O9wMd4IBYXVz6/5xozMmiTW+DvrpO5R2aWKKhYZ9p4sf7a7Dr5Q7V5endXhuZvOflHI3RLhYUg2ZqMHTYmRQ9r6CfcPmvzXDYGwjm9ZNJ4u3NKkDHJM5Vk+M9DjwSNTV7OwcKMyBMu4+13GRHdBlESQDBg4wMcSf/d2Xcresqe8hiYCSwdscr+RZmwibED94yfyLZzspIrbbmBSbFEB7Hgu5Tp/ETTtDrUgBo1a0gK0/UGac3fXjLAKCRRX6SkNg+a8HnD+IPDKPl4wA/HkoFK9cUwFnlVugkoUvNF5+4z9kKlyq8269+nPpTAdpfC8v2VUsWo3FmMxK8c/ZtOBs9eJpnKI2jJW4/nA00Ugy8UuLv63wHmc1pRPuWHaqKxMJgshixcQV6AVfz6djQ+UHYWqDfuPc77fkv9bQH2j/fZKClYg0623lNIaP50pFE3d4jxpNjKigz138UyRA4icLum+1X0un7K867Qo7/TC7XKEleRtSfta0LR+UUlMYHvfMWtQKuoRWrrUjbZH9dlUBxOeS2H4uNuEJlYILpV5p6Aw013G8I83X2J1+3L1hg+R2rdSptPjZUExE+I1Q0EZuWiSRTB59w+PF7Uu6AJhpLyGcvpM7wsL+gDfKm+vR7U1jxWcZviGnIpojrPqXeyqgXwea5cZcNlFDn+/79oSO3sOsnGklTs7ycLO3R6rxW8IX0atH2y/Q6ncER4DGOqHpxeHPY71A==
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: javazone
      name: javazone
      namespace: default
    type: Opaque

