[project]
name = "main"
version = "0.0.0"
dependencies = [
    "jinja2"
]

[tool.uv.sources]
dagger-io = { path = "sdk", editable = true }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

