#!/bin/bash
# [MISE] description="Reseal the secret"
# [MISE] tools={"aqua:kubectl" = "latest", "kubeseal" = "latest"}
# [MISE] outputs=["deploy/sealed-secret.yaml"]

echo "TODO: Get secret values from fnox!"
exit 1

echo "---" > sealed-secret.yaml
kubectl create secret generic --dry-run=client --namespace default -ojson javazone --from-env-file=.env | \
    jq '.metadata.labels.app="javazone"' | \
    kubeseal -ojson | \
    jq '.metadata.labels.app="javazone"' | \
    yq -Poyaml >> deploy/sealed-secret.yaml
